class: base--STYLED
colors: 5
images:
  - http://www.placecage.com/c/500/300: Crazy Cage
  - images/waiting.gif: Cookie Waiting
  - images/charge.gif: Napoleon Charging on a Penguin
  - http://www.placecage.com/1920/1080: Calm Cage
descriptors:
  - Oh Wow
  - Such Movement
  - Many Styles
  - Great Abstract

